// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNGDFyEVzCvR7e4rFYffD_tAeeWwQHZWk',
    appId: '1:1020739408229:web:b708b9f76290a63665d18c',
    messagingSenderId: '1020739408229',
    projectId: 'edtech-app-26eb7',
    authDomain: 'edtech-app-26eb7.firebaseapp.com',
    storageBucket: 'edtech-app-26eb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr7zw02eLVc7JeIUR_pWDeHm8utIxba5I',
    appId: '1:1020739408229:android:441a087ae2a1741365d18c',
    messagingSenderId: '1020739408229',
    projectId: 'edtech-app-26eb7',
    storageBucket: 'edtech-app-26eb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFqZp_N6SvY2VDwHY0vXPSfedL3RXl8c',
    appId: '1:1020739408229:ios:a5a0608f8dce407665d18c',
    messagingSenderId: '1020739408229',
    projectId: 'edtech-app-26eb7',
    storageBucket: 'edtech-app-26eb7.firebasestorage.app',
    iosBundleId: 'com.example.edtechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFqZp_N6SvY2VDwHY0vXPSfedL3RXl8c',
    appId: '1:1020739408229:ios:a5a0608f8dce407665d18c',
    messagingSenderId: '1020739408229',
    projectId: 'edtech-app-26eb7',
    storageBucket: 'edtech-app-26eb7.firebasestorage.app',
    iosBundleId: 'com.example.edtechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNGDFyEVzCvR7e4rFYffD_tAeeWwQHZWk',
    appId: '1:1020739408229:web:e7f0dec990e9cc8665d18c',
    messagingSenderId: '1020739408229',
    projectId: 'edtech-app-26eb7',
    authDomain: 'edtech-app-26eb7.firebaseapp.com',
    storageBucket: 'edtech-app-26eb7.firebasestorage.app',
  );
}
